FROM python:3.10-slim

WORKDIR /app

COPY requirements.database-service.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY ./src/db ./src/db
COPY ./src/db/advanced_manager.py ./main.py

EXPOSE 8007

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8007"] 