FROM python:3.10-slim

WORKDIR /app

COPY requirements.speech-recognizer.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY ./src/audio ./src/audio
COPY ./src/audio/main.py ./main.py

EXPOSE 8003

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8003"] 