FROM python:3.10-slim

WORKDIR /app

COPY requirements.sentiment-analyzer.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY ./src/text ./src/text
COPY ./src/text/advanced_analysis.py ./main.py

EXPOSE 8005

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8005"] 