global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'callytics-local'
    environment: 'development'

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus 자체 모니터링
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Callytics 애플리케이션 모니터링
  - job_name: 'callytics'
    static_configs:
      - targets: ['callytics:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Node Exporter (시스템 메트릭)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # Docker 컨테이너 메트릭 (옵션)
  # - job_name: 'docker'
  #   static_configs:
  #     - targets: ['docker-host:9323']

# 알람 매니저 설정 (옵션)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#           - alertmanager:9093 