runtime:
  device: "cuda"                                       # Options: "cpu", "cuda"
  compute_type: "float16"                              # Options: "int8", "float16"
  cuda_alloc_conf: "expandable_segments:True"          # PyTorch CUDA Memory Management

language:
  audio: "ko"                                          # Options: "en", "tr", "ko"
  text: "ko"                                           # Options: "en", "tr", "ko"

# OpenAI API 설정 (ChatGPT 분석용)
openai:
  api_key: "${OPENAI_API_KEY}"                         # OpenAI API 키
  model: "gpt-4"                                       # 사용할 모델
  max_tokens: 2000                                     # 최대 토큰 수
  temperature: 0.1                                     # 생성 다양성
  timeout: 30                                          # API 호출 타임아웃 (초)

# 화자 분리 설정
diarization:
  auth_token: "${HUGGINGFACE_TOKEN}"                   # HuggingFace 인증 토큰
  model: "pyannote/speaker-diarization-3.1"           # 화자 분리 모델
  min_speakers: 1                                      # 최소 화자 수
  max_speakers: 10                                     # 최대 화자 수

# 음성 인식 설정
whisper:
  model: "base"                                        # Whisper 모델 크기 (tiny/base/small/medium/large)
  language: "ko"                                       # 기본 언어
  suppress_numerals: false                             # 숫자 억제 여부

models:
  # 기존 모델들
  llama:
    model_name: "meta-llama/Llama-3.2-3B-Instruct"     # Options: "meta-llama/Llama-3.2-3B-Instruct", etc.
    huggingface_api_key: "${HUGGINGFACE_TOKEN}"

  openai:
    model_name: "gpt-4o"                               # Options: "gpt-4", "gpt-4o", etc.
    openai_api_key: "${OPENAI_API_KEY}"

  azure_openai:
    model_name: "gpt-4o"                               # Options: "gpt-4", "gpt-4o", etc.
    azure_openai_api_key: "${AZURE_OPENAI_API_KEY}"
    azure_openai_api_base: "${AZURE_OPENAI_API_BASE}"
    azure_openai_api_version: "${AZURE_OPENAI_API_VERSION}"

  mpsenet:
    model_name: "JacobLinCool/MP-SENet-DNS"            # Options: "JacobLinCool/MP-SENet-DNS", "JacobLinCool/MP-SENet-VB"

  # 한국어 특화 모델들
  korean_models:
    openchat:
      model_type: "openchat"
      base_model_name: "../AI 모델/model/openchat-3.5-0106-private"
      peft_model_name: ""                              # PEFT 모델 경로 (있는 경우)
      device: "auto"
      torch_dtype: "bfloat16"
      max_new_tokens: 1024
      temperature: 0.1
      use_flash_attention: true
      
    llama3:
      model_type: "llama3"
      base_model_name: "../AI 모델/model/Meta-Llama-3-8B-Instruct-private"
      peft_model_name: ""
      device: "auto"
      torch_dtype: "bfloat16"
      max_new_tokens: 1024
      temperature: 0.1
      use_flash_attention: true
      
    gemma:
      model_type: "gemma"
      base_model_name: "../AI 모델/model/gemma-2b-it-private"
      peft_model_name: ""
      device: "auto"
      torch_dtype: "bfloat16"
      max_new_tokens: 1024
      temperature: 0.1
      use_flash_attention: false

# 통합 상담 분석 설정
integrated_analysis:
  enabled: true
  default_model: "gpt-4"                               # 기본 ChatGPT 모델
  fallback_model: "openchat"                           # 폴백 모델 (로컬)
  
  # 분석 옵션
  analysis_options:
    business_type_classification: true                 # 업무 유형 분류
    consultation_type_classification: true             # 상담 유형 분류
    detail_classification: true                        # 세부 분류
    result_evaluation: true                            # 상담 결과 평가
    summary_generation: true                           # 요약 생성
    solution_proposal: true                            # 해결방안 제시
    
  # 임계값 설정
  thresholds:
    confidence_min: 0.5                                # 최소 신뢰도
    processing_timeout: 60                             # 처리 타임아웃 (초)
    max_file_size: 100                                 # 최대 파일 크기 (MB)
    
  # 상담 분류 체계
  business_types:
    - "요금 안내"
    - "요금 납부"
    - "요금제 변경"
    - "선택약정 할인"
    - "납부 방법 변경"
    - "부가서비스 안내"
    - "소액 결제"
    - "휴대폰 정지 분실 파손"
    - "기기변경"
    - "명의 번호 유심 해지"
    - "그 외 업무유형"
    
  classification_types:
    - "상담 주제"
    - "상담 요건"
    - "상담 내용"
    - "상담 사유"
    - "상담 결과"
    
  detail_classifications:
    consultation_topic:
      - "상품 및 서비스 일반"
      - "주문 결제 입금 확인"
      - "취소 반품 교환 환불 AS"
      - "회원 관리"
      - "배송 문의"
      - "이벤트 할인"
      - "콘텐츠"
      - "제휴"
      - "기타"
    consultation_requirement:
      - "단일 요건 민원"
      - "다수 요건 민원"
    consultation_content:
      - "일반 문의 상담"
      - "업무 처리 상담"
      - "고충 상담"
    consultation_reason:
      - "업체"
      - "민원인"
    consultation_result:
      - "만족"
      - "미흡"
      - "해결 불가"
      - "추가 상담 필요"

# LG U+ 민원 분석 설정
complaint_analysis:
  enabled: true
  default_model: "openchat"                            # 기본 사용 모델
  fallback_model: "openai"                             # 폴백 모델
  
  # 분석 옵션
  analysis_options:
    classification: true
    sentiment_analysis: true
    priority_evaluation: true
    department_assignment: true
    summary_generation: true
    qa_generation: true
    
  # 임계값 설정
  thresholds:
    confidence_min: 0.5
    sentiment_threshold: -0.2
    priority_high: 3
    urgency_high: "High"
    
  # LG U+ 업무 분야 설정
  categories:
    - name: "요금 안내"
      keywords: ["요금제", "안내", "계산", "요금", "문의", "얼마", "비용", 
                "가격", "금액", "청구", "요금표", "할인", "프로모션"]
    - name: "요금 납부"
      keywords: ["납부", "결제", "입금", "미납", "연체", "납부일", "납부방법"]
    - name: "요금제 변경"
      keywords: ["요금제", "변경", "신청", "교체", "업그레이드", "다운그레이드"]
    - name: "선택약정 할인"
      keywords: ["선택약정", "할인", "약정", "혜택", "할인율", "약정기간"]
    - name: "납부 방법 변경"
      keywords: ["납부방법", "자동이체", "신용카드", "현금납부", "변경"]
    - name: "부가서비스 안내"
      keywords: ["부가서비스", "부가", "서비스", "가입", "해지", "안내"]
    - name: "소액 결제"
      keywords: ["소액결제", "소액", "결제", "신청", "확인", "오류"]
    - name: "휴대폰 정지/분실/파손"
      keywords: ["정지", "분실", "파손", "고장", "교체", "수리", "신고"]
    - name: "기기변경"
      keywords: ["기기", "변경", "교체", "업그레이드", "이전", "새폰"]
    - name: "명의/번호/유심 해지"
      keywords: ["명의", "번호", "유심", "해지", "변경", "이전"]
    - name: "기타"
      keywords: []

  # 상담 주제 설정
  topics:
    - name: "상품 및 서비스 일반"
      keywords: ["상품", "서비스", "일반", "문의", "안내"]
    - name: "주문/결제/입금 확인"
      keywords: ["주문", "결제", "입금", "확인", "처리"]
    - name: "취소/반품/교환/환불/AS"
      keywords: ["취소", "반품", "교환", "환불", "AS", "수리"]
    - name: "회원 관리"
      keywords: ["회원", "관리", "정보", "계정", "변경"]
    - name: "배송 문의"
      keywords: ["배송", "택배", "배달", "수령", "지연"]
    - name: "이벤트/할인"
      keywords: ["이벤트", "할인", "프로모션", "혜택", "쿠폰"]
    - name: "콘텐츠"
      keywords: ["콘텐츠", "게임", "음악", "동영상", "앱"]
    - name: "제휴"
      keywords: ["제휴", "파트너", "협력", "서비스"]
    - name: "기타"
      keywords: []

  # 상담 내용 유형 설정
  consultation_types:
    - name: "일반 문의 상담"
      keywords: ["문의", "안내", "질문", "궁금", "알고싶"]
    - name: "업무 처리 상담"
      keywords: ["신청", "처리", "변경", "해지", "가입", "교체"]
    - name: "고충 상담"
      keywords: ["불만", "고충", "문제", "어려움", "힘들", "짜증"]

  # LG U+ 부서 설정
  departments:
    # 홈 서비스 부서
    home_services:
      - name: "홈서비스일반상담"
        keywords: ["인터넷", "TV", "IoT", "일반", "문제해결", "정보변경"]
      - name: "홈서비스기술상담"
        keywords: ["장애", "품질", "단말기", "A/S", "기술", "고장"]
      - name: "홈서비스가입상담"
        keywords: ["가입", "신청", "혜택", "안내", "접수"]
      - name: "홈가치제안상담"
        keywords: ["해지", "재약정", "요금할인", "불편사항", "제안"]
    
    # 모바일 서비스 부서
    mobile_services:
      - name: "모바일일반상담"
        keywords: ["휴대폰", "일반", "문제해결", "요금제", "컨설팅"]
      - name: "SAVE상담"
        keywords: ["해지", "분실", "파손", "맞춤", "혜택"]
      - name: "통화품질상담"
        keywords: ["통화품질", "통화", "품질", "문제해결"]
      - name: "전문상담"
        keywords: ["로밍", "유플러스샵", "cyber", "외국인", "알뜰폰"]

# 데이터베이스 설정
database:
  path: "Callytics_new.sqlite"                        # SQLite 데이터베이스 파일 경로
  timeout: 30                                         # 연결 타임아웃 (초)
  backup_enabled: true                                # 백업 활성화
  backup_interval: 24                                 # 백업 간격 (시간)

# 성능 모니터링 설정
performance:
  enabled: true
  log_interval: 60                                    # 로그 간격 (초)
  memory_threshold: 80                                # 메모리 사용률 임계값 (%)
  cpu_threshold: 90                                   # CPU 사용률 임계값 (%)
  batch_size: 2           # 1→2 (처리량 증가)
  max_workers: 6          # 4→6 (병렬 처리 확대)
  memory_limit: "12GB"    # 8GB→12GB (여유 확보)
  
# 로깅 설정
logging:
  level: "INFO"                                       # 로그 레벨
  file_path: "logs/callytics.log"                     # 로그 파일 경로
  max_file_size: "100MB"                              # 최대 파일 크기
  backup_count: 10                                    # 백업 파일 개수

# 성능 설정 (통합됨)
# performance:
#   batch_size: 1
#   max_workers: 4
#   memory_limit: "8GB"
#   gpu_memory_fraction: 0.8

# API 설정
api:
  enabled: false
  host: "localhost"
  port: 8000
  cors_origins: ["*"]
  rate_limit: 100  # requests per minute 